services:
  rstudio_environoment_dan:
    image: rocker/rstudio:4.1.3
    ports:
      - "8887:8787"
    volumes:
      - .:/home/rstudio/my_project_files_dan
    environment:
      # PASSWORD: apassword
      DISABLE_AUTH: true

  rstudio_environoment_tony:
    image: rocker/rstudio:4.1.3
    ports:
      - "8889:8787"
    volumes:
      - .:/home/rstudio/my_project_files_tony
    environment:
      PASSWORD: apassword
      #DISABLE_AUTH: true
